### ISSUE TITLE
AttributeError: 'Xlnk' object has no attribute 'bufmap'

### ISSUE THREAD

**Issue by hopesala** [TomG008/SkyNet#19]
Successfully uninstalled pynq-2.5.1
Successfully installed pynq-2.5.3
(base) cao@cao-OMEN-by-HP-Desktop-PC-880-p0xx:/media/cao/SkyNet-master/FPGA/Deploy$ sudo python3 SkyNet.py 

**** Running SkyNet
Traceback (most recent call last):
  File "SkyNet.py", line 20, in <module>
    xlnk = Xlnk()
  File "/usr/local/lib/python3.8/dist-packages/pynq/xlnk.py", line 136, in __init__
    Xlnk._open_library(Xlnk.libxlnk_path)
  File "/usr/local/lib/python3.8/dist-packages/pynq/xlnk.py", line 122, in _open_library
    cls.libxlnk = cls.ffi.dlopen(path)
  File "/usr/local/lib/python3.8/dist-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.8/dist-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.8/dist-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/usr/lib/libcma.so': /usr/lib/libcma.so: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/libcma.so'
Exception ignored in: <function Xlnk.__del__ at 0x7f7df96fc700>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pynq/xlnk.py", line 150, in __del__
AttributeError: 'Xlnk' object has no attribute 'bufmap'

**Comment by hopesala** [comment]
Additionally, ctypes.util.find_library() did not manage to locate a library called '/usr/lib/libcma.so'
libcma.so,  how to have it installed
